### ISSUE TITLE
Code in notebook is unmanagable

### ISSUE THREAD

**Issue by cthoyt** [ComPath/resources#2]
There are tons of functions defined in this notebook: https://github.com/ComPath/resources/blob/master/notebooks/Mappings%20Similarity%20Analysis.ipynb

Aren't these generally reusable? It would be much better to have them living in one of the repositories (like https://github.com/ComPath/compath) so the notebook can focus more on the analysis instead of the software

**Comment by ddomingof** [comment]
Included in PathMe
